package src.entities.space;

/**
 * Created by Vincent on 06/11/2019.
 */
public enum TileSprite {

    EMPTY, BLANK_1,
    HORIZONTAL_WALL, BLANK_2,
    VERTICAL_WALL, BLANK_3,
    BOT_LEFT_CORNER_WALL, BLANK_4,
    BOT_RIGHT_CORNER_WALL, BLANK_5,
    TOP_RIGHT_CORNER_WALL, BLANK_6,
    TOP_LEFT_CORNER_WALL, BLANK_7,
    INT_RIGHT_TOP_LEFT_WALL, BLANK_8,
    INT_TOP_LEFT_DOWN_WALL, BLANK_9,
    INT_LEFT_DOWN_RIGHT_WALL, BLANK_10,
    INT_DOWN_RIGHT_TOP_WALL, BLANK_11,
    INT_QUAD_WALL, BLANK_12,
    LONE_WALL, BLANK_13,
    EXT_LEFT_WALL, BLANK_14,
    EXT_DOWN_WALL, BLANK_15,
    EXT_RIGHT_WALL, BLANK_16,
    EXT_TOP_WALL, BLANK_18,
    TOP_LEFT_CORNER_WALL_BIG, BLANK_19,
    TOP_RIGHT_CORNER_WALL_BIG, BLANK_20,
    BOT_LEFT_CORNER_WALL_BIG, BLANK_21,
    BOT_RIGHT_CORNER_WALL_BIG, BLANK_22,
    BERRY, BLANK_23,
    INVINCIBILITY, BLANK_24
}
