package src.entities.moving.specific;

public enum PacmanSprite {
    PACMAN_RIGHT, BLANK_1,
    PACMAN_DOWN, BLANK_2,
    PACMAN_LEFT, BLANK_3,
    PACMAN_UP, BLANK_4,
    PACMAN_STATIC, BLANK_5,

    PACMAN_RIGHT_WALL, BLANK_6,
    PACMAN_DOWN_WALL, BLANK_7,
    PACMAN_LEFT_WALL, BLANK_8,
    PACMAN_UP_WALL, BLANK_9,
    PACMAN_STATIC_WALL, BLANK_10,

    PACMAN_RIGHT_INV, BLANK_11,
    PACMAN_DOWN_INV, BLANK_12,
    PACMAN_LEFT_INV, BLANK_13,
    PACMAN_UP_INV, BLANK_14,
    PACMAN_STATIC_INV, BLANK_15,
}
